Refactored input request for distro selection

diff --git a/new_installs/after_new_install b/new_installs/after_new_install
--- a/new_installs/after_new_install
+++ b/new_installs/after_new_install
@@ -21,6 +21,22 @@ distro="none"
 # Functions
 #############################################################################
 
+function getDistro() {
+  echo -e "Which Linux distro are you using?\na) Arch\nb) Solus\nc) Ubuntu"
+  DISTRO_CHOICE="none"
+  read DISTRO_CHOICE
+  if [[ $DISTRO_CHOICE == "a" || $DISTRO_CHOICE == "arch" || $DISTRO_CHOICE == "Arch" ]]; then
+    distro="arch"
+  elif [[ $DISTRO_CHOICE == "b" || $DISTRO_CHOICE == "solus" || $DISTRO_CHOICE == "Solus" ]]; then
+    distro="solus"
+  elif [[ $DISTRO_CHOICE == "c" || $DISTRO_CHOICE == "ubuntu" || $DISTRO_CHOICE == "Ubuntu" ]]; then
+    distro="ubuntu"
+  else
+    echo "Invalid selection. Aborting script."
+    exit 1
+  fi
+}
+
 function updater() {
   if [[ $distro == "solus" ]]; then
     echo ""
@@ -94,27 +110,6 @@ function installer() {
   fi
 }
 
-# TODO: Fix the repo function; remember that Solus uses a name reference when
-# adding repos
-function addRepo() {
-  if [[ $distro == "solus" ]]; then
-    sudo eopkg add-repo -y $1 $1
-    sudo eopkg enable-repo $1
-  elif [[ $distro == "arch" ]]; then
-    echo "I haven't made a repo process for Arch; repo ignored: "
-    echo " > $1"
-  else
-    # TODO: Just change this into a for loop for n arguments
-    if [[ $# -eq 1 ]]; then
-      sudo add-apt-repository -y $1
-    elif [[ $# -eq 2 ]]; then
-      sudo add-apt-repository -y $1 $2
-    fi
-  fi
-}
-
-# (all unsorted)
-
 #while [[ $awaiting ]]
 #do
 #  echo "testing: press y to quit, n to loop"
@@ -127,11 +122,6 @@ function addRepo() {
 #############################################################################
 # Installation processes
 #############################################################################
-
-# Update repo info
-updater
-# Just in case...
-upgrader
 
 # Check if arguments were passed
 if [[ $# -eq 1 ]]; then
@@ -146,10 +136,16 @@ if [[ $# -eq 1 ]]; then
     echo "Distro set to $distro"
   fi
 else
-  echo "No arguments were passed. Defaulted distro to: $distro. Is this okay? (y/n)"
-
-  exit 1
+  # If no args were passed, ask which distro is being used
+  getDistro
 fi
+
+# Update repo info
+updater
+# Check for current available upgrades prior to installations
+upgrader
+
+
 ###############################################
 # Start installers...                         #
 ###############################################
@@ -207,6 +203,7 @@ installer python-dev
 installer python3-dev
 sudo pip install --upgrade pip
 
+installer fonts-powerline
 installer powerline-fonts
 #wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
 #wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
